### ISSUE TITLE
Display name does not change for friendrequest/author["friend"]

### ISSUE THREAD

**Issue by r-hu1** [CMPUT404-Fall2016/cmput404-project#22]
Step:
Create 2 user
user 1 search user 2
add friend
user 1 go to friend tab to see request (or accept the request and check the friend display name)
user 2 change display name
user 1 refresh page
display name on friendrequest does not change

**Comment by stat3kk** [comment]
This seems like an edge case and I wouldn't worry too much about it if it takes a long time to fix. There are higher priority issues unless it's related to a deeper bug.
