### ISSUE TITLE
front-end bug when adding a foreign author as friend

### ISSUE THREAD

**Issue by touqir14** [CMPUT404-Fall2016/cmput404-project#26]
When a foreign author sends me a friend request and I add him as a friend, the clientside doesnt send the server the friend request sender's name(probably the value is an empty string) which is why in the author_relationships table that field is blank for this entry. However the client is sending me my name and this is why I see my name in that row. @stat3kk @WeiLing5

**Comment by WeiLing5** [comment]
So you want author1_name as their name and author2_name as your name?

**Comment by stat3kk** [comment]
Fixed as of commit 7a31b43c8ced5dd2b4b05f9033a1feda9c4e2505.
