### ISSUE TITLE
US 3: As a server admin, images can be hosted on my server

### ISSUE THREAD

**Issue by williums** [CMPUT404-Fall2016/cmput404-project#29]
The current implementation is that images are base64 encoded and sent to the server, and after that I don't know what happens to it. I assume the base64 encoded string is just stored in a list with the post itself. Problem is, the user story is that our server can HOST the image, i.e. the image has a unique url and I should get a url to that image rather than the base64 encoded image.

**Comment by Boyuan-Gu** [comment]
Should work now?
