### ISSUE TITLE
When searching for a non-existent author, the page should notify the user about it.

### ISSUE THREAD

**Issue by touqir14** [CMPUT404-Fall2016/cmput404-project#35]
@stat3kk @WeiLing5

**Comment by WeiLing5** [comment]
The alert is working for status code 200, but its not working for status 404

**Comment by stat3kk** [comment]
What do we get from the server if we search for a non-existent author? Do we get a 200 along with something like NO_MATCH? Or just a 404? If so, I might make a generic 404 page
